### ISSUE TITLE
German "u.a." is not always read out correctly

### ISSUE THREAD

**Issue by claell** [petergtz/alexa-wikipedia#36]
I noticed that the abbreviation "u.a." is read out as "und andere". That is sometimes correct, but in my case it should read out as "unter anderem". Is this caused by the Skill or the TTS service from Alexa?

**Comment by petergtz** [comment]
Hi @claell, this is very difficult to get right, because it is indeed the TTS service from Alexa. So I'm taking whatever the Wikipedia API gives me, and pass it on to the Alexa service. I guess in this case the only thing we can hope for is that Alexa gets better at this.

**Comment by claell** [comment]
Ah ok. I was not sure where the issue originated. Thanks for letting me know.

**Comment by petergtz** [comment]
Okay, cool. I'll close this issue for now, but feel free to re-open if you want to further discuss.

**Comment by claell** [comment]
I am ok with having this closed, because it is not caused by the Skill. I was not sure how you handle such issues, so I did not close it myself.

I have created an issue for this now on my unofficial Alexa issue tracker, so it does not get lost: https://gitlab.com/clel/amazon-alexa-issue-tracker/issues/11
