### ISSUE TITLE
Add link to GitHub on Amazon description

### ISSUE THREAD

**Issue by petergtz** [petergtz/alexa-wikipedia#8]
This should make it possible for users to provide feedback.

**Comment by claell** [comment]
Thanks for adding the link, that made me aware of this repo. Nice to have the code open sourced on GitHub and thanks for this nice skill.

Is it possible to make the link clickable? That would make it even easier to visit the GitHub page.

**Comment by petergtz** [comment]
Hi @claell,

I'm glad you like it!

> Is it possible to make the link clickable? That would make it even easier to visit the GitHub page.

Unfortunately not. The description is provided as plain text.

**Comment by claell** [comment]
Alright. Sad that Amazon has set it this way and there is apparently no intent to change it in the near future, for reference:
- https://forums.developer.amazon.com/questions/72147/can-the-full-skill-description-contain-a-html-link.html
- https://forums.developer.amazon.com/questions/116349/can-i-create-a-hyperlink-in-the-skill-description.html

**Comment by petergtz** [comment]
Yes, indeed. Thanks for the links for reference though. I'll close this issue for now. Let's revisit some time in the future.
